### ISSUE TITLE
CHAT DESIGN

### ISSUE THREAD

**Issue by Marwaxhello** [IvarSchuyt/connecting-people-my-first-chatroom#4]
Misschien kan je dit weghalen om anders zetten

<img width="230" alt="Screenshot 2023-05-26 at 11 14 55" src="https://github.com/IvarSchuyt/connecting-people-my-first-chatroom/assets/112861555/34407038-9a3b-4c1c-a6e0-2e5fbde090f4">

**Comment by IvarSchuyt** [comment]
Dat is alleen als mensen een super lang woord spammen
